### ISSUE TITLE
Please elaborate

### ISSUE THREAD

**Issue by Kiragroh** [LDClark/PDFtoAria#1]
Hi LDClark,

your upload is a coool coincidence. I tired ARIA-Access a few weeks ago. I could get the API-keys and succed with a simple request (from the myVarian-webinar):

string apiKey = "YourAPIKey";
            string request = "{\"__type\":\"GetMachineListRequest:http://services.varian.com/AriaWebConnect/Link\",\"Attributes\":null,\"DepartmentID\":{\"Value\":\"Radiation Oncology\"}}";
            string response = SendData(request, true, apiKey);
            Console.WriteLine(response);
            var response_machines = JsonConvert.DeserializeObject<GetMachineListResponse>(response);
            foreach(var machine in response_machines.Machines)
            {
                Console.WriteLine(machine.MachineId.Value);
            }
            Console.ReadLine();

but more complex requests in regards to appointments and documents fail.

I work on a TBox. Can you elaborate on the required Service Package or your pitfalls at the beginning? Hopefully, this could explain my problems.

Will definitely try your upload. At the moment we are working with the eDoc-Printer and I have to build many specific protocols. The DocumentAPI-workflow would be better in some cases.

Kind regards

**Comment by LDClark** [comment]
I tried using Oncology Services for several days on our TBox and one day
noticed that I couldn't access Documents at all.  I placed a ticket and
later found out Oncology Services wasn't installed properly on the Tbox.
After it was fixed I had no issues using InsertDocumentRequest.

Aria Access looks interesting.  This solution doesn't use it, but I'd like
to learn more about it.  Access to the machine schedule would be really
nice.

Landon

**Comment by Kiragroh** [comment]
I could try it today on our new TBox for Eclipse/ARIA16.1 (GoLive in January). Here I have AriaWebServices1.4 installed and all works great.
I tihink I will add Dropdown menus for DocumentTypes, PDF-Merge functionality (if needed) and automatic PatID-Detection.

Thank again for sharing

**Comment by LDClark** [comment]
Merging is very much needed.  I'd like to see an implementation of OCR somewhere in here.  Thanks for trying it out, I'm glad its working.

**Comment by LDClark** [comment]
Merging somewhat works now.
